# Git Commands
alias g = 'git'
alias ga = 'git add'
alias gb = 'git branch'
alias gc = 'git commit'
alias gcm = 'git commit -m'
alias gco = 'git checkout'
alias gcob = 'git checkout -b'
alias gs = 'git status'
alias gi = 'git init'
alias gl = 'git log'
alias gpll = 'git pull'
alias gpllo = 'git pull origin'
alias gpsh = 'git push'
alias gpsus = 'git push --set=upstream origin $(git_current_branch)'
alias gr = 'git remote'
alias gs = 'git status'
